name: Push to GitHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Push to Master
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto-commit from GitHub Actions"
        git push https://samedfft2634:${{ PAT }}@github.com/samedfft2634/samedfft2634.git HEAD:master
